import turtle
turtle.shape("turtle")
turtle.begin_fill()
turtle.color("yellow")
for i in range(60):
    turtle.right(6)
    turtle.forward(10)
turtle.end_fill()
turtle.right(120)
turtle.forward(60)
turtle.begin_fill()
turtle.color("blue")
for i in range(60):
    turtle.right(6)
    turtle.forward(1)
turtle.end_fill()
turtle.penup()
turtle.left(120)
turtle.forward(50)
turtle.left(120)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
for i in range(60):
    turtle.right(6)
    turtle.forward(1)
turtle.end_fill()
turtle.penup()
turtle.left(90)
turtle.forward(25)
turtle.left(60)
turtle.pendown()
turtle.width(5)
turtle.color("black")
turtle.forward(40)
turtle.penup()
turtle.left(45)
turtle.forward(50)
turtle.pendown()
turtle.color("red")
turtle.right(90)
for i in range(12):
    turtle.right(6)
    turtle.forward(5)
